### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by davidsowerby** [drmaas/ratpack-kotlin#12]
Tried updating to 0.9.0 from 0.6.0 and saw failure below.  Also tried 0.7.0, and that failed in the same way.  You can access my code [here](https://github.com/davidsowerby/simplycd-agent).  

Commit 3be9d8ccab06a1a14cd249c1977e6876a3e1aa72 runs all tests successfully with your dsl at 0.6.0, but fails when updated. 

I was using IDEA, and that generated an automatic error report as well.

> Information:Kotlin: Kotlin JPS plugin version 1.1.1
Information:Kotlin: Plugin loaded: KotlinAndroidJpsPlugin
Information:Kotlin: Using kotlin-home = /home/david/idea/plugins/Kotlin/kotlinc
Information:Kotlin: Kotlin Compiler version 1.1.1
Information:Module "simplycd-agent_main" was fully rebuilt due to project configuration/dependencies changes
Information:10/04/17 14:08 - Compilation completed with 1 error and 0 warnings in 8s 377ms
Error:Kotlin: [Internal Error] org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't inline method call 'ratpack' into
@kotlin.jvm.JvmStatic public final fun main(args: kotlin.Array<kotlin.String>): kotlin.Unit defined in uk.q3c.simplycd.agent.app.Main[SimpleFunctionDescriptorImpl@532e5a15]
@JvmStatic fun main(args: Array<String>) {
        ratpack {
            serverConfig {
                development(true)
                port(9000)
            }
            bindings {
                add(ObjectMapper::class.java, HalMapper())
                module(BuildModule())
                module(ApiModule())
                module(GlobalBusModule())
                module(I18NModule())
                module(LifecycleModule())
                module(ProjectModule())
                module(QueueModule())
                module(SystemModule())
                module(GitPlusModule())
                module(ValidationModule())
            }
            handlers {
                path(subscriptions, SubscriptionHandler::class.java)
                path(buildRequests, BuildRequestHandler::class.java)
                path(buildRecords, BuildRecordHandler::class.java)
                path(hook, SubscriptionHandler::class.java)
                all(RootHandler::class.java)
            }
        }
    }
Cause: Not generated
Cause: Cannot inline bytecode of class ratpack/kotlin/handling/RatpackKt which has version 52. This compiler can only inline Java 1.6 bytecode (version 50)
File being compiled and position: (23,9) in /home/david/git/simplycd-agent/src/main/kotlin/uk/q3c/simplycd/agent/app/Main.kt
PsiElement: ratpack {
            serverConfig {
                development(true)
                port(9000)
            }
            bindings {
                add(ObjectMapper::class.java, HalMapper())
                module(BuildModule())
                module(ApiModule())
                module(GlobalBusModule())
                module(I18NModule())
                module(LifecycleModule())
                module(ProjectModule())
                module(QueueModule())
                module(SystemModule())
                module(GitPlusModule())
                module(ValidationModule())
            }
            handlers {
                path(subscriptions, SubscriptionHandler::class.java)
                path(buildRequests, BuildRequestHandler::class.java)
                path(buildRecords, BuildRecordHandler::class.java)
                path(hook, SubscriptionHandler::class.java)
                all(RootHandler::class.java)
            }
        }
The root cause was thrown at: InlineCodegenUtil.java:157
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.throwCompilationException(InlineCodegen.java:203)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.genCallInner(InlineCodegen.java:189)
	at org.jetbrains.kotlin.codegen.CallGenerator.genCall(CallGenerator.kt:104)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2893)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2846)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:44)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:23)
	at org.jetbrains.kotlin.codegen.OperationStackValue.putSelector(StackValue.kt:65)
	at org.jetbrains.kotlin.codegen.StackValueWithLeaveTask.putSelector(StackValue.kt:57)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:108)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:101)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.putStackValue(ExpressionCodegen.java:350)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.gen(ExpressionCodegen.java:335)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.returnExpression(ExpressionCodegen.java:2257)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$FunctionDefault.doGenerateBody(FunctionGenerationStrategy.java:49)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$CodegenBased.generateBody(FunctionGenerationStrategy.java:69)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:493)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:254)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:175)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.gen(FunctionCodegen.java:146)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genSimpleMember(MemberCodegen.java:190)
	at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateDeclaration(ClassBodyCodegen.java:133)
	at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateBody(ClassBodyCodegen.java:76)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:127)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:285)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:269)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassOrObject(PackageCodegenImpl.java:162)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassesAndObjectsInFile(PackageCodegenImpl.java:86)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:124)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:66)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.generatePackage(KotlinCodegenFacade.java:99)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.doGenerateFiles(KotlinCodegenFacade.java:77)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:44)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:417)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules(KotlinToJVMBytecodeCompiler.kt:151)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:170)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:55)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:191)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.execCompiler(CompileServiceImpl.kt:399)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.access$execCompiler(CompileServiceImpl.kt:95)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1.invoke(CompileServiceImpl.kt:362)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1.invoke(CompileServiceImpl.kt:95)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$2$$special$$inlined$withValidClientOrSessionProxy$lambda$1.invoke(CompileServiceImpl.kt:750)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$2$$special$$inlined$withValidClientOrSessionProxy$lambda$1.invoke(CompileServiceImpl.kt:95)
	at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:777)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.access$checkedCompile(CompileServiceImpl.kt:95)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$2.invoke(CompileServiceImpl.kt:749)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$2.invoke(CompileServiceImpl.kt:95)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.ifAlive(CompileServiceImpl.kt:930)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.ifAlive$default(CompileServiceImpl.kt:817)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:743)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.access$doCompile(CompileServiceImpl.kt:95)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1.invoke(CompileServiceImpl.kt:360)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1.invoke(CompileServiceImpl.kt:95)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.ifAlive(CompileServiceImpl.kt:930)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.ifAlive$default(CompileServiceImpl.kt:817)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:339)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:324)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException: Cannot inline bytecode of class ratpack/kotlin/handling/RatpackKt which has version 52. This compiler can only inline Java 1.6 bytecode (version 50)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegenUtil.assertVersionNotGreaterThanGeneratedOne(InlineCodegenUtil.java:157)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegenUtil$1.visit(InlineCodegenUtil.java:108)
	at org.jetbrains.org.objectweb.asm.ClassReader.accept(ClassReader.java:622)
	at org.jetbrains.org.objectweb.asm.ClassReader.accept(ClassReader.java:506)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegenUtil.getMethodNode(InlineCodegenUtil.java:105)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.doCreateMethodNodeFromCompiled(InlineCodegen.java:351)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.access$000(InlineCodegen.java:76)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen$1.invoke(InlineCodegen.java:277)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen$1.invoke(InlineCodegen.java:274)
	at org.jetbrains.kotlin.codegen.inline.InlineCacheKt.getOrPut(InlineCache.kt:34)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.createMethodNode(InlineCodegen.java:273)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.genCallInner(InlineCodegen.java:179)
	... 73 more

**Comment by drmaas** [comment]
Hi David - 

Looks like you are targeting java6 bytecode. Is that intentional? ratpack-kotlin is compiled and tested against java8.
```
Caused by: java.lang.UnsupportedOperationException: Cannot inline bytecode of class ratpack/kotlin/handling/RatpackKt which has version 52. This compiler can only inline Java 1.6 bytecode (version 50)
```
 Try adding the following to your build.gradle:
```
compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```
See https://kotlinlang.org/docs/reference/using-gradle.html for reference. 

Also ensure in Intellij that the project facets -> jvmTarget is detected at 1.8.

I ran my sample application against java8 with the above jvmTarget, with the following main:
```
object Application {
  @JvmStatic
  fun main(args: Array<String>) {
    ratpack {
      serverConfig {
        ServerConfigurer.config(this)
        require("/cassandra", CassandraRatpackProperties::class.java)
      }
      bindings {
        module(StarterModule(serverConfig))
        module(CassandraModule::class.java) {
          it.useRatpackEventLoop = true
        }
        module(ApplicationModule::class.java)
      }
      handlers {
        prefix("cars", FlowableCarChain::class.java)
        prefix("cars2", PromiseCarChain::class.java)
        prefix("search", RedskyChain::class.java)
      }
    }
  }
```

And I was unable to reproduce the error when doing a simple curl command.

**Comment by davidsowerby** [comment]
Hi - great, that was simple.  That bit of Kotlin knowledge was missing from my head - this must be the first time I've used a JVM 1.8 feature from Kotlin, despite writing quite a bit of Kotlin.

I had the usual Gradle compatibility settings, but clearly that was not sufficient:

```
sourceCompatibility = '1.8'
targetCompatibility = '1.8'
```

Thanks for the comprehensive answer
